<?php /** @var Dibs_EasyCheckout_Block_Checkout $this */ ?>
<script type="text/javascript" src="<?php echo $this->getDibsCheckoutJsUrl() ?>"></script>
<div id="dibs-complete-checkout"></div>
<script>
    //<![CDATA[
    var checkoutOptions = {
        checkoutKey: '<?php echo $this->getCheckoutKey() ?>',
        paymentId : '<?php echo $this->getPaymentId() ?>',
        containerId : 'dibs-complete-checkout',
        language: '<?php echo $this->getCheckoutLanguage() ?>',
    };
    var checkout = new Dibs.Checkout(checkoutOptions);

    checkout.on('payment-completed', function(response) {
        window.location = '<?php echo $this->getDibsCheckoutValidateUrl() ?>';
    });
    //]]>
</script>