<?php /** @var Dibs_EasyCheckout_Block_Totals $this */?>

<?php $shippingMethods = $this->getShippingMethods(); ?>
<?php if($shippingMethods): ?>
    <div class="dibs-easy-checkout-section">
        <div id="dibs-easy-shipping-title" class="dibs-easy-ctrl-title"><?php echo $this->__('Shipping Methods'); ?></div>
        <div id="dibs-easy-shipping-methods">
            <ul>
                <?php foreach($shippingMethods as $code=>$method): ?>
                    <?php $class = $method['active'] ? 'dibs-easy-shipping-selector dibs-easy-active': 'dibs-easy-shipping-selector dibs-easy-non-active'; ?>
                    <li class="dibs-easy-shipping-method-wrapper <?= $class ?>" id="<?= $code ?>">
                        <p onclick="updateView({action:'set-shipping-method', shipping_rate_code: '<?= $code ?>'})"><span><?= $method['carrier_title'] .' - '. $method['method_title'] ?></span> - <span><?php echo Mage::helper('core')->currency($method['price'], true, false) ?></span></p>
                        <div class="<?= $code ?>-shipping-details"></div>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif;?>

<div class="dibs-easy-checkout-section">
    <div id="dibs-easy-ordersummary-title" class="dibs-easy-ctrl-title"><?php echo $this->__('Order Summary')?></div>
    <table id="totals-table">
        <tbody>
        <?php $cartTotals = $this->getCartTotals(); ?>
        <?php foreach($cartTotals as $key=>$value): ?>
            <?php if($value['id'] != 'grand_total') :?>
                <tr id="tr-<?= $key ?>" >
                    <td class="dibs-easy-totals-label" id="dibs-easy-totals-label-<?= $value['id'] ?>" id="dibs-easy-totals-label-<?= $value['id'] ?>"><?= $value['label'] ?></td>
                    <td class="dibs-easy-totals-total" id="dibs-easy-totals-<?= $value['id'] ?>" id="dibs-easy-totals-<?= $value['id'] ?>" align="right"><?= $value['value'] ?></td>
                </tr>
            <?php endif;?>
        <?php endforeach; ?>
        <tr id="coupon_tr">
            <td style="width: 120px;">
                <div class="block discount" id="block-discount" data-collapsible="true" role="tablist">
                    <div class="" id="coupon-title" onclick="couponControl(this)">
                        <strong id="block-discount-heading" role="heading" aria-level="2">✚ <?php echo $this->__('Apply Discount Code'); ?></strong>
                    </div>
                    <div id="coupon-form" style="display: none;">
                        <form id="discount-coupon-form" method="post" action="<?= $this->getCouponUrl()?>">
                            <?php if($this->getCouponCode()): ?>
                                <input type="hidden" name="remove" value="1">
                            <?php endif; ?>
                            <input type="hidden" name="return_url" value="<?= $this->getCheckoutUrl()?>">
                            <div class="">
                                <input type="hidden" name="remove" id="remove-coupon" value="0">
                                <div class="field" style="float:left;">
                                    <div class="control">
                                        <input type="text" class="input-text" id="coupon_code" name="coupon_code" value="<?= $this->getCouponCode() ?>" <?php if($this->getCouponCode()) {echo "disabled";} ?>  placeholder="Enter discount code" value="">
                                    </div>
                                </div>
                                <div class="primary">
                                    <button id="easy-coupon-button-submit" class="action apply primary" type="submit">
                                        <?php if(!$this->getCouponCode()): ?>
                                            <span data-bind="text: coupon_button_label"><?php echo $this->__('Applied Discount'); ?></span>
                                        <?php endif; ?>
                                        <?php if($this->getCouponCode()): ?>
                                            <span data-bind="text: coupon_button_label"><?php echo $this->__('Remove Discount Code'); ?></span>
                                        <?php endif; ?>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </td>
            <td></td>
        </tr>
        <?php foreach($cartTotals as $key=>$value): ?>
            <?php if($value['id'] == 'grand_total') :?>
                <tr id="tr-<?= $key ?>">
                    <td class="dibs-easy-totals-label" id="dibs-easy-totals-label-<?= $value['id'] ?>" id="dibs-easy-totals-label-<?= $value['id'] ?>">
                        <span><?php echo $this->__('Grand total'); ?> <?php if ($value['tax']>0) : ?>(<?php echo $this->__('Incl.'); ?> <?php echo $value['tax']; ?>)<?php endif; ?></span>
                    </td>
                    <td class="dibs-easy-totals-total" id="dibs-easy-totals-<?= $value['id'] ?>" id="dibs-easy-totals-<?= $value['id'] ?>" align="right">
                        <?= $value['value'] ?>
                    </td>
                </tr>
            <?php endif;?>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>